# Generated by Django 3.0 on 2022-06-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='Mobaile',
            new_name='Mobile',
        ),
    ]
